services:

  app:
    build:
      context: .docker/php
    container_name: symfony-app
    volumes:
      - .:/srv/app
      - /etc/localtime:/etc/localtime:ro
      - ./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:ro
    working_dir: /srv/app
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - TZ=Europe/Vienna
    depends_on:
      - database

  database:
    image: mariadb:${MARIADB_VERSION:-10.11}
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw

  caddy:
    image: caddy:2-alpine
    container_name: symfony-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/srv/app/public
      - ./.docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  messenger-consumer:
    build:
      context: .docker/php
    container_name: consumer-app
    environment:
      - TZ=Europe/Vienna
    volumes:
      - .:/srv/app
      - ./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:ro
    working_dir: /srv/app
    depends_on:
      - app
    command: php bin/console messenger:consume async scheduler_FetchEnergyFeedScheduler --no-interaction
    restart: unless-stopped

volumes:
  database_data:
  caddy_data:
  caddy_config: