services:

  app:
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - TZ=Europe/Vienna
      # - DATABASE_URL=${DATABASE_URL}
    volumes: []

  database:
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}

  caddy:
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

  messenger-consumer:
    environment:
      - TZ=Europe/Vienna
    volumes: []
